version: "3"

services: 
        webtest:
                image: yeydaproj/webtest
                ports: 
                - 8080:8080
                restart: always
                environment: 
                - TZ=Europe/Kiev
